name = "KDL"
grammar = "kdl"
path_suffixes = ["kdl"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
autoclose_before = ",]}"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
]
